import pandas as pd

class ParseError(Exception):
    """
    Exception representing an error parsing a Flux CSV file.
    """
    pass

def read_annotated_csv(
    file_path: str,
    delimiter: str = ',',
    comment_prefix: str = '#',
    cast_columns: bool = True,
    merge_tables: bool = False
) -> pd.DataFrame|list[pd.DataFrame]:
    """
    Read an Annotated CSV file generated by Flux and converts it into a table.
    The table is represented by a pandas 'DataFrames' where each column type
    depends on the table datatype definition.

    The specification of an Annotated CSV file can be found
    [here](https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/).

    Args:
        file_path (str): Path to the CSV.
        delimiter (str): Character used as column separator.
        comment_prefix (str): Character used as annotation line prefix.
        cast_columns (bool): If True the columns are casted to the correct type
            specified by the datatype annotation row.
        merge_table (bool): If True returns a single 'DataFrame' with all the tables
            merged togheter, otherwise returns a list of 'Dataframe's one for each table.

    Returns:
        DataFrame or list: If 'merge_tables' is True returns a single 'DataFrame' with
            all the tables merged together, otherwise returns a list of 'DataFrames'
            one for each table present in the CSV file.

    Raises:
        ParseError: If the file is malformed or there are some errors parsing the tables.
    """
    # possible states of the parsing FSM.
    STATE_NEW_TABLE = 0
    STATE_PARSE_RECORD = 1
    STATE_END_TABLE = 2

    # open
    with open(file_path, 'r') as csv_file:
        file_content = [row.rstrip() for row in csv_file.readlines()]

    complete_tables = []
    current_table_types = []
    current_table_header = []
    current_table_records = []
    current_state = STATE_NEW_TABLE
    idx = 0
    while idx < len(file_content):
        if current_state == STATE_NEW_TABLE:
            # parse 3 annotation rows and 1 header row
            if len(file_content) < idx + 4:
                raise ParseError(
                    ("Parsing a malformed table. "
                    "Not enough rows for annotation and header")
                )
            current_table_types = _parse_annotation_rows(
                file_content[idx:idx+3],
                delimiter,
                comment_prefix
            )
            current_table_header = _parse_header_row(
                file_content[idx+3],
                delimiter
            )
            idx += 4
            current_state = STATE_PARSE_RECORD
        elif current_state == STATE_PARSE_RECORD:
            table_row_content = file_content[idx]

            # it's an empty row?
            if len(table_row_content) == 0:
                current_state = STATE_END_TABLE
            else:
                # parse table row
                row_values = table_row_content.split(delimiter)[1:]
                if len(row_values) != len(current_table_header):
                    # TODO: skip the row without raising an exception
                    raise ParseError(
                        ("Parsing a row with different number of elements "
                        f"than the header ({len(row_values)} != {len(current_table_header)})")
                    )
                current_table_records.append(row_values)
            idx += 1
        elif current_state == STATE_END_TABLE:
            if len(file_content[idx]) == 0:
                # skip empty rows
                idx += 1
            elif file_content[idx].startswith(comment_prefix):
                # if this row is an annotation row end the
                # current table an start a new one
                df = _table_to_dataframe(
                    current_table_records,
                    current_table_header,
                    current_table_types,
                    cast_columns
                )
                complete_tables.append(df)
                current_table_types = []
                current_table_header = []
                current_table_records = []
                current_state = STATE_NEW_TABLE
            else:
                # otherwise try to parse a row on the current table
                current_state = STATE_PARSE_RECORD
        else:
            raise ParseError(f"Unknown parser state: '{current_state}'")

    # append the last remaining table to the completed if there's something
    if len(current_table_header) > 0:
        df = _table_to_dataframe(
            current_table_records,
            current_table_header,
            current_table_types,
            cast_columns
        )
        complete_tables.append(df)

    if merge_tables:
        return pd.concat(complete_tables,ignore_index=True)
    return complete_tables

def _parse_header_row(
    row: str,
    delimiter: str
) -> list[str]:
    """
    Parse the header row of a table.

    The header row defines the columns labels. There is only an header row per table.

    Args:
        row (str): The header row as a string.
        delimiter (str): Character used as column separator.

    Returns:
        list: The names of the columns as a list of strings.

    Raises:
        Exception: If the header row is malformed.
    """
    header = row.split(delimiter)[1:]
    if len(header) == 0:
        raise ParseError(f"Malformed header row: '{row}'")
    return header

def _parse_annotation_rows(
    rows: list[str],
    delimiter: str,
    comment_prefix: str
) -> list[str]:
    """
    Parse the annotation rows at the start of a table.

    Annotation rows describe column properties and start with comment_prefix value.
    The first column in an annotation row always contains the annotation name.
    The annotation name can be one of this:
        - datatype Describes the type of data or which line protocol element the column represents.
        - group Indicates the column is part of the group key.
        - default Value to use for rows with an empty value.

    In particular, a datatype can have one of this values: (i) boolean, (ii) unsignedLong, (iii) long,
    (iv) double, (v) string, (vi) base64Binary, (vii) dateTime, (viii) duration.

    Args:
        rows (list[str]): The 3 annotation rows as a list of strings.
        delimiter (str): character used as column separator.
        comment_prefix (str): character prefixing the annotation rows.

    Returns:
        list: A list of strings representing the datatypes.

    Raises:
        Exception: If the annotation rows are malformed.
    This function will return the data
    """
    datatypes = []
    if len(rows) != 3:
        raise ParseError(
            ("Malformed annotation rows. "
            "A table must have exactly 3 annotation rows, "
            f"but {len(rows)} was found.")
        )

    for row in rows:
        if not row.startswith(comment_prefix):
            raise ParseError(f"Malformed annotation row: '{row}'")
        values = row.split(delimiter)
        annotation_col = values[0]
        annotation_col_rest = values[1:]
        if annotation_col == '#group':
            pass
        elif annotation_col == '#datatype':
            datatypes = annotation_col_rest
        elif annotation_col == '#default':
            pass
        else:
            raise ParseError(f"Unknown annotation column type: '{annotation_col}'")
    return datatypes

def _table_to_dataframe(
    records: list[str],
    header: list[str],
    types: list[str],
    cast_columns: bool
):
    """
    Convert given table to a pandas DataFrame.

    This function converts a table represented as a list of strings to a pandas DataFrame
    where each column has the correct name from the header and it's casted to the correct type.

    Args:
        records (list): The rows of the table as a list of strings.
        header (list): The column labels as a list of strings.
        types (list): A list of strings representing the type of each column.
        cast_columns (bool): If True the columns are casted to the correct type
            specified by the datatype annotation row.

    Returns:
        DataFrame: A pandas DataFrame representing the table.

    Raises:
        Exception: If there is some error casting the data.
    """
    df = pd.DataFrame(records, columns=header)
    if cast_columns:
        for i in range(len(header)):
            col = header[i]
            type = types[i]

            try:
                if type == 'boolean':
                    # boolean, bool, “true” or “false”
                    df[col] = df[col].astype('bool')
                elif type == 'unsignedLong':
                    # unsignedLong, uint, unsigned 64-bit integer
                    df[col] = df[col].astype('uint64')
                elif type == 'long':
                    # long, int, signed 64-bit integer
                    df[col] = df[col].astype('int64')
                elif type == 'double':
                    # double, float, IEEE-754 64-bit floating-point number
                    df[col] = df[col].astype('float64')
                elif type == 'string':
                    # string, string, UTF-8 encoded string
                    df[col] = df[col].astype('str')
                elif type == 'base64Binary':
                    # base64Binary, bytes, base64 encoded sequence of bytes as defined in RFC 4648
                    df[col] = df[col].astype('object')
                elif type.startswith('dateTime'):
                    # datetime, time, instant in time, may be followed with a
                    # colon : and a description of the format (number, RFC3339, RFC3339Nano)
                    # TODO: dateTime:number can raise an exception when converting to datetime
                    #   find if we need to use a different method to convert unix timestamps.
                    df[col] = pd.to_datetime(df[col], format='ISO8601')
                elif type == 'duration':
                    # duration, duration, length of time represented as an
                    # unsigned 64-bit integer number of nanoseconds
                    df[col] = df[col].astype('uint64')
                else:
                    raise ParseError(f"Unsupported type: '{type}'")
            except Exception as ex:
                raise ParseError(f"Error converting column: '{col}' to flux type: '{type}'. {ex}")
    return df
